// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq77gqlB2-BFwfB5d4f5fJir_-KlJhlpk',
    appId: '1:522166475301:web:d596083f0d60237a443dcc',
    messagingSenderId: '522166475301',
    projectId: 'planespott-ad6b6',
    authDomain: 'planespott-ad6b6.firebaseapp.com',
    storageBucket: 'planespott-ad6b6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOvXd-fFXseZ7GpxCzi8qFrI7g0Tp1CnA',
    appId: '1:522166475301:android:c6de49dd9fc8e36d443dcc',
    messagingSenderId: '522166475301',
    projectId: 'planespott-ad6b6',
    storageBucket: 'planespott-ad6b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-JWYZyROLjscKynucrTLDrtJ0oNqlJ3E',
    appId: '1:522166475301:ios:ee06d5e99bed0206443dcc',
    messagingSenderId: '522166475301',
    projectId: 'planespott-ad6b6',
    storageBucket: 'planespott-ad6b6.firebasestorage.app',
    iosBundleId: 'com.example.planespott',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-JWYZyROLjscKynucrTLDrtJ0oNqlJ3E',
    appId: '1:522166475301:ios:ee06d5e99bed0206443dcc',
    messagingSenderId: '522166475301',
    projectId: 'planespott-ad6b6',
    storageBucket: 'planespott-ad6b6.firebasestorage.app',
    iosBundleId: 'com.example.planespott',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq77gqlB2-BFwfB5d4f5fJir_-KlJhlpk',
    appId: '1:522166475301:web:bbb28ad8c2d5ad06443dcc',
    messagingSenderId: '522166475301',
    projectId: 'planespott-ad6b6',
    authDomain: 'planespott-ad6b6.firebaseapp.com',
    storageBucket: 'planespott-ad6b6.firebasestorage.app',
  );

}